### ISSUE TITLE
wrong device in modify_fs_v2.sh

### ISSUE THREAD

**Issue by jconallen** [IBM-ICP-CoC/ICP-311-Install#8]
I am not sure, but I think that in line 22 of the modify_fs_v2.sh file, the the device should be /dev/xvdc not /dev/xvde.

Can someone confirm this?

**Comment by dwakeman** [comment]
Good question, not sure.  Either way there might still be a bug in the script.  We create two separate volume groups, one for `/var` and one for `/opt`.  On lines 14-16 we create them:

```
#Create Volume Groups
vgcreate opt-vg /dev/xvdc
vgcreate var-vg /dev/xvde
```

On lines 28-29 we mount them:

```
mkdir /mnt/newopt ; mount /dev/xvde /mnt/newopt
mkdir /mnt/newvar ; mount /dev/xvde /mnt/newvar
```

I think on line 28 we should be mounting `/mnt/newopt` on `/dev/xvdc` not `/dev/xvde`.

@kriersd thoughts on this?

**Comment by jconallen** [comment]
yes, good point.  I think we can modify this script to only set up one disk, as the /opt space is no longer required.  I've been using this script just for /dev/xvdc  for /var  in my latest installs.  Perhaps we can just update the script for /var?

**Comment by kriersd** [comment]
Yep.. I think this is a bug.. line 28 should have been xvdc.  I will modify that.. I will commit that and then make another modification to just update the VAR directory. We no longer need to increase the size of OPT.
